
spring:
  application:
    name: nativedemo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/nativedemo
    username: nativedemo
    password: Hello.nativedemo
  sql:
    init:
      schema-locations: classpath*:cn/nboot/nativedemo/initdata/schema/*.sql
      data-locations: classpath*:cn/nboot/nativedemo/initdata/data/*.sql
      mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: true
  h2:
    console:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  file:
    name: logs/${spring.application.name}.log
server:
  port: 8080
