spring:
  application:
    name: nativedemo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/nativedemo
    username: nativedemo
    password: Hello.nativedemo
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  thymeleaf:
    mode: HTML
    suffix: .html
  h2:
    console:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  file:
    name: logs/${spring.application.name}.log
server:
  port: 8080
