management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    cn.nboot.nativedemo.initdata: debug
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nativedemo
    username: postgres
    password: 123