name: native image linux

on:
  workflow_dispatch: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for GraalVM JDK 11
        uses: graalvm/setup-graalvm@v1
        with:
          version: 22.0.0.2
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env: # Or as an environment variable
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: mvn clean -U spring-boot:build-image --file pom.xml --no-transfer-progress
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for GraalVM JDK 11
      uses: graalvm/setup-graalvm@v1
      with:
        version: 22.0.0.2
        java-version: 11
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn clean -U -Pnative --file pom.xml --no-transfer-progress package
    - name: Upload artifact # 上传构建产物
      uses: actions/upload-artifact@v3.0.0
      with:
        name: native-demo
        path: target/nd-native-demo-*